name: Deploy docscrape chart

on:
  workflow_dispatch:
    inputs:
      triggered_repo:
        description: |
          The repo that triggered deploy.
          It also is an image
        type: string
        required: true
      tag:
        description: "The image tag"
        type: string
        required: true


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out docscrape chart
        uses: actions/checkout@master
        with:
          repository: ${{ github.repository_owner }}/docscrape_chart
          token: ${{ secrets.DEPLOY_PAT }}
      - run: git pull

      - name: Update ${{ inputs.triggered_repo }} image tag in docscrape chart
        run: |
          sed -i '/^${{ inputs.triggered_repo }}:/{n;s/image:.*/image: ghcr.io\/docscrape\/${{ inputs.triggered_repo }}:${{ inputs.tag }}/;}' values.yaml
          cat values.yaml

          git config --global user.email `git log -n 1 --pretty=format:%ae`
          git config --global user.name `git log -n 1 --pretty=format:%an`
          git commit values.yaml -m "Update ${{ inputs.triggered_repo }} tag to ${{ inputs.tag }}"

      # - name: "Push chart with updated ${{ inputs.triggered_repo }} with tag: ${{ inputs.tag }}"
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.DEPLOY_PAT }}
      #     branch: master

      - run: echo ${{ secrets.VK_ID_TO_SEND_DEBUG_REPORTS_TO }}

      # - name: Deploy
      #   uses: deliverybot/helm@master
      #   with:
      #     release: docscrape
      #     namespace: test
      #     chart: docscrape_chart
      #     token: ${{ github.token }}
      #     values: |
      #       dockerconfigjson: ${{ secrets.DOCKERCONFIGJSON }}

      #       post_search_engine.vk_login: ${{ secrets.POST_SEARCH_ENGINE_VK_LOGIN }}
      #       post_search_engine.vk_password: ${{ secrets.POST_SEARCH_ENGINE_VK_PASSWORD }}

      #       account_finder.fc_login: ${{ secrets.FC_LOGIN }}
      #       account_finder.fc_password: ${{ secrets.FC_PASSWORD }}

      #       seller.vk_login: ${{ secrets.SELLER_VK_LOGIN }}
      #       seller.vk_password: ${{ secrets.SELLER_VK_PASSWORD }}
      #       seller.vk_id_to_send_debug_reports_to: ${{ secrets.VK_ID_TO_SEND_DEBUG_REPORTS_TO }}
      #       seller.billing_number: ${{ secrets.BILLING_NUMBER }}
      #       seller.dev_mode: "true"

      #     value-files: "values.yaml"
      #     # value-files: >-
      #     # [
      #     #   "values.yaml", 
      #     #   "values.production.yaml"
      #     # ]

      #   env:
      #     KUBECONFIG_FILE: '${{ secrets.KUBECONFIG_FILE }}'
 
