name: Deploy docscrape chart

on:
  workflow_dispatch:
    inputs:
      triggered_repo:
        description: |
          The repo that triggered deploy.
          It also is an image
        type: string
        required: true
      tag:
        description: "The image tag"
        type: string
        required: true


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out docscrape chart
        uses: actions/checkout@master
        with:
          repository: ${{ github.repository_owner }}/docscrape_chart
          token: ${{ secrets.DEPLOY_PAT }}

      - name: Update ${{ inputs.triggered_repo }} image tag in docscrape chart
        run: |
          sed -i '/^${{ inputs.triggered_repo }}:/{n;s/image:.*/image: "ghcr.io/docscrape/${{ inputs.triggered_repo }}:${{ inputs.tag }}"/;}' values.yaml
      
      - run: cat values.yaml

    # set images to values.yaml
    # commit values.yaml back to chart repo
    # set configs & secrets from deploy environment to values.yaml
    # install chart with helm
