name: Deploy docscrape chart

on:
  workflow_dispatch:
    inputs:
      trigger_repo:
        description: "The repo that triggered deploy"
        type: string
        required: true


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: ls

      - name: Check out docscrape chart
        uses: actions/checkout@master
        with:
          repository: ${{ github.repository_owner }}/docscrape_chart
          token: ${{ secrets.DEPLOY_PAT }}

      - run: ls
        
      # - run: echo ${{ inputs.trigger_repo }}
    # get docscrape chart code
    # set images to values.yaml
    # commit values.yaml back to chart repo
    # set configs & secrets from deploy environment to values.yaml
    # install chart with helm
